CREATE TABLE user
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    passhash VARCHAR(128) NOT NULL,
    salt VARCHAR(128) NOT NULL
);
CREATE UNIQUE INDEX id_UNIQUE ON user ( id );
CREATE UNIQUE INDEX username_UNIQUE ON user ( username );